# Generated by Django 3.1.3 on 2020-12-03 10:03

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sakary',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
