# Generated by Django 3.1.3 on 2020-12-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_sluge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sluge',
            new_name='slug',
        ),
    ]
